# Generated by Django 3.1.14 on 2022-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_user_confidence_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owntracks_deviceid',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owntracks_username',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
