# Generated by Django 3.1.14 on 2022-09-29 08:19

import api.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220929_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('duration', models.IntegerField()),
                ('geodata', models.JSONField()),
                ('map_viz', models.JSONField()),
                ('card_thumbnail', models.JSONField()),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('public', models.BooleanField(db_index=True, default=False)),
                ('cover_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_user', to='api.photo')),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.Photo')),
                ('shared_to', models.ManyToManyField(related_name='trip_user_shared_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'owner')},
            },
        ),
    ]
